=== kiinami/lisa-vulkan/scenes/scene.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="floatList">
        <xs:restriction base="xs:string">
            <xs:pattern value="[-+]?\d*\.?\d+([eE][-+]?\d+)?([ ,]+[-+]?\d*\.?\d+([eE][-+]?\d+)?)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="scene">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entity" maxOccurs="unbounded">
                    <xs:complexType>

                        <xs:all>

                            <!-- Transform -->
                            <xs:element name="transform" minOccurs="0">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:choice maxOccurs="unbounded">
                                            <xs:element name="translate">
                                                <xs:complexType>
                                                    <xs:attribute name="value" type="floatList" use="required"/>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="rotate">
                                                <xs:complexType>
                                                    <xs:attribute name="axis" type="floatList" use="required"/>
                                                    <xs:attribute name="angle" type="xs:float" use="required"/>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="scale">
                                                <xs:complexType>
                                                    <xs:attribute name="value" type="floatList" use="required"/>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:choice>
                                        <xs:element name="lookat">
                                            <xs:complexType>
                                                <xs:attribute name="origin" type="floatList" use="required"/>
                                                <xs:attribute name="target" type="floatList" use="required"/>
                                                <xs:attribute name="up" type="floatList" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="matrix">
                                            <xs:complexType>
                                                <xs:attribute name="value" type="floatList" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>

                            <!-- Mesh -->
                            <xs:element name="mesh" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="type" type="xs:string" use="required"/>
                                    <xs:attribute name="path" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>

                            <!-- Material -->
                            <xs:element name="material" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="color" type="floatList" use="required"/>
                                    <xs:attribute name="roughness" type="xs:float" use="required"/>
                                    <xs:attribute name="metallic" type="xs:float" use="required"/>
                                </xs:complexType>
                            </xs:element>

                            <!-- Texture -->
                            <xs:element name="texture" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="diffuse" type="xs:string" use="required"/>
                                    <xs:attribute name="roughness" type="xs:string" default=""/>
                                    <xs:attribute name="metallic" type="xs:string" default=""/>
                                </xs:complexType>
                            </xs:element>

                            <!-- Camera -->
                            <xs:element name="camera" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="fov" type="xs:float"/>
                                    <xs:attribute name="aspect_ratio" type="xs:float"/>
                                    <xs:attribute name="near_plane">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:float">
                                                <xs:minExclusive value="0"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="far_plane">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:float">
                                                <xs:minExclusive value="0"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>

                            <!-- Directional Light -->
                            <xs:element name="directional_light" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="color" type="floatList" use="required"/>
                                    <xs:attribute name="intensity" type="xs:float" use="required"/>
                                </xs:complexType>
                            </xs:element>

                            <!-- Point Light -->
                            <xs:element name="point_light" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="color" type="floatList" use="required"/>
                                    <xs:attribute name="intensity" type="xs:float" use="required"/>
                                    <xs:attribute name="attenuation" type="xs:float" use="required"/>
                                    <xs:attribute name="radius" type="xs:float" use="required"/>
                                </xs:complexType>
                            </xs:element>

                        </xs:all>

                        <xs:attribute name="name" type="xs:string"/>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== kiinami/lisa-vulkan/scenes/material_test/material_test.xml
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../scene.xsd">
    <entity name="sphere1">
        <transform>
            <translate value="3, 0, 0"/>
        </transform>
        <mesh type="obj" path="models/sphere.obj"/>
        <material color="0.5 0.0 0.0" roughness="0.05" metallic="0.0"/>
    </entity>
    <entity name="sphere2">
        <transform>
            <translate value="1, 0, 0"/>
        </transform>
        <mesh type="obj" path="models/sphere.obj"/>
        <material color="0.5 0.0 0.0" roughness="1.0" metallic="0.0"/>
    </entity>
    <entity name="sphere3">
        <transform>
            <translate value="-1, 0, 0"/>
        </transform>
        <mesh type="obj" path="models/sphere.obj"/>
        <material color="0.5 0.0 0.0" roughness="0.05" metallic="1.0"/>
    </entity>
    <entity name="sphere4">
        <transform>
            <translate value="-3, 0, 0"/>
        </transform>
        <mesh type="obj" path="models/sphere.obj"/>
        <material color="0.5 0.0 0.0" roughness="1" metallic="1"/>
    </entity>
    <entity name="sun_light">
        <transform>
            <lookat origin="0, 0, 0" target="0, -1, -1" up="0, 1, 0"/>
        </transform>
        <directional_light color="0.6 0.2 0.2" intensity="100.0"/>
    </entity>
    <entity name="main_camera">
        <transform>
            <lookat origin="0, 2, 10" target="0, 0, 0" up="0, 1, 0"/>
        </transform>
        <camera/>
    </entity>
</scene>

=== kiinami/lisa-vulkan/scenes/simple/simple.xml
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../scene.xsd">
    <entity name="monkey0">
        <transform>
            <translate value="0, 0, 0"/>
        </transform>
        <mesh type="obj" path="./models/suzanne.obj"/>
        <texture path="./textures/suzanne0.ktx"/>
    </entity>
    <entity name="monkey1">
        <transform>
            <translate value="2, 0, 0"/>
        </transform>
        <mesh type="obj" path="./models/suzanne.obj"/>
        <texture path="./textures/suzanne1.ktx"/>
    </entity>
    <entity name="monkey2">
        <transform>
            <translate value="-2, 0, 0"/>
        </transform>
        <mesh type="obj" path="./models/suzanne.obj"/>
        <texture path="./textures/suzanne2.ktx"/>
    </entity>
    <entity>
        <transform>
            <lookat origin="0, 0, 5" target="0, 0, 0" up="0, 1, 0"/>
        </transform>
        <camera/>
    </entity>
</scene>

=== kiinami/lisa-vulkan/scenes/game/game.xml
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../scene.xsd">
    <external file="game.glb">
        <transform>
            <translate value="0, 0, 0"/>
            <scale value="3.0"/>
        </transform>
    </external>

    <entity name="main_camera">
        <transform>
            <lookat origin="0, 1, 4" target="0, 1, 0" up="0, 1, 0"/>
        </transform>
        <camera/>
    </entity>

    <entity name="sun_light">
        <transform>
            <lookat origin="0, 0, 0" target="0, -1, -1" up="0, 1, 0"/>
        </transform>
        <directional_light color="1.0, 0.9, 0.8" intensity="10"/>
    </entity>

    <entity name="ambient_light">
        <ambient_light color="1.0, 0.9, 0.8" intensity="1"/>
    </entity>
</scene>

=== kiinami/lisa-vulkan/scenes/shadows/shadows.xml
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../scene.xsd">
    <entity name="main_camera">
        <transform>
            <lookat origin="0.0, 0.8, 1.8" target="0.0, 0.18, 0.0" up="0, 1, 0"/>
        </transform>
        <camera fov="16"/>
    </entity>

    <entity name="tower">
        <transform>
            <translate value="0 0 0"/>
        </transform>
        <mesh path="models/tower.obj"/>
        <material albedo="0.2 0.12 0.08" metallic="0.0" roughness="0.8"/>
    </entity>

    <entity name="bridge">
        <transform>
            <translate value="0 0 0"/>
        </transform>
        <mesh path="models/bridge.obj"/>
        <material albedo="0.2 0.12 0.08" metallic="0.0" roughness="0.8"/>
    </entity>

    <entity name="floor">
        <transform>
            <translate value="0 0 0"/>
        </transform>
        <mesh path="models/floor.obj"/>
        <material albedo="0.0 0.8 0.2" metallic="0.0" roughness="0.8"/>
    </entity>

    <entity name="tree">
        <transform>
            <translate value="0 0 0"/>
        </transform>
        <mesh path="models/tree.obj"/>
        <material albedo="1.0 0.0 0.0" metallic="0.0" roughness="0.8"/>
    </entity>

    <entity name="river">
        <transform>
            <translate value="0 0 0"/>
        </transform>
        <mesh path="models/river.obj"/>
        <material albedo="0.0 0.02 1.0" metallic="0.5" roughness="0.2"/>
    </entity>

    <entity name="ambient_light">
        <transform>
            <translate value="0 0 0"/>
        </transform>
        <ambient_light color="1 1 1" intensity="0.1"/>
    </entity>

    <entity name="light">
        <transform>
            <translate value="-0.25 0.5 0.5"/>
        </transform>
        <point_light color="0.8 0.5 0.5" intensity="20" attenuation="0.1" radius="2" cast_shadows="true"/>
    </entity>
</scene>

=== kiinami/lisa-vulkan/scenes/lighting_test/lighting_test.xml
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../scene.xsd">

    <entity name="monkey_center">
        <transform>
            <translate value="0, 0, 0"/>
        </transform>
        <mesh path="models/suzanne.obj"/>
        <material albedo="1.0, 1.0, 1.0" roughness="0.1" metallic="1.0"/>
    </entity>

    <entity name="monkey_left">
        <transform>
            <translate value="-3, 0, 0"/>
            <rotate axis="0, 1, 0" angle="45"/>
        </transform>
        <mesh path="models/suzanne.obj"/>
        <material albedo="0.8, 0.8, 0.8" roughness="0.3" metallic="1.0"/>
    </entity>

    <entity name="monkey_right">
        <transform>
            <translate value="3, 0, 0"/>
            <rotate axis="0, 1, 0" angle="-45"/>
        </transform>
        <mesh path="models/suzanne.obj"/>
        <material albedo="0.2, 0.2, 0.2" roughness="0.05" metallic="0.0"/>
    </entity>

    <entity name="main_camera">
        <transform>
            <lookat origin="0, 2, 8" target="0, 0, 0" up="0, 1, 0"/>
        </transform>
        <camera/>
    </entity>

    <entity name="sun_light">
        <transform>
            <lookat origin="0, 0, 0" target="-1, -1, -1" up="0, 1, 0"/>
        </transform>
        <directional_light color="1.0, 0.9, 0.8" intensity="1.5"/>
    </entity>

    <entity name="red_point_light">
        <transform>
            <translate value="-3, 1, 2"/>
        </transform>
        <point_light color="1.0, 0.1, 0.1" intensity="50.0" attenuation="1.0" radius="10.0"/>
    </entity>

    <entity name="blue_point_light">
        <transform>
            <translate value="3, -1, 2"/>
        </transform>
        <point_light color="0.1, 0.1, 1.0" intensity="50.0" attenuation="1.0" radius="10.0"/>
    </entity>

    <entity name="green_point_light">
        <transform>
            <translate value="0, 3, -2"/>
        </transform>
        <point_light color="0.1, 1.0, 0.1" intensity="30.0" attenuation="1.0" radius="15.0"/>
    </entity>
</scene>

=== kiinami/lisa-vulkan/scenes/ssao_test/ssao_test.xml
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../scene.xsd">
    <entity name="cat">
        <transform>
            <translate value="0, 0, 0"/>
            <scale value="10.0"/>
        </transform>
        <mesh type="obj" path="models/cat.obj"/>
    </entity>

    <entity name="main_camera">
        <transform>
            <lookat origin="0, 1, 4" target="0, 1, 0" up="0, 1, 0"/>
        </transform>
        <camera/>
    </entity>

    <entity name="ambient_light">
        <ambient_light color="1.0, 0.9, 0.8" intensity="1"/>
    </entity>
</scene>

=== kiinami/lisa-vulkan/scenes/cat/cat.xml
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../scene.xsd">
    <entity name="cat">
        <transform>
            <translate value="0, 0, 0"/>
            <scale value="10.0"/>
        </transform>
        <mesh type="obj" path="models/cat.obj"/>
    </entity>

    <entity name="main_camera">
        <transform>
            <lookat origin="0, 2, 8" target="0, 0, 0" up="0, 1, 0"/>
        </transform>
        <camera/>
    </entity>


    <entity name="sun_light">
        <transform>
            <lookat origin="0, 0, 0" target="-1, -1, -1" up="0, 1, 0"/>
        </transform>
        <directional_light color="1.0, 0.9, 0.8" intensity="1.5"/>
    </entity>

    <entity name="red_point_light">
        <transform>
            <translate value="-3, 1, 2"/>
        </transform>
        <point_light color="1.0, 0.1, 0.1" intensity="50.0" attenuation="1.0" radius="10.0"/>
    </entity>

    <entity name="blue_point_light">
        <transform>
            <translate value="3, -1, 2"/>
        </transform>
        <point_light color="0.1, 0.1, 1.0" intensity="50.0" attenuation="1.0" radius="10.0"/>
    </entity>

    <entity name="green_point_light">
        <transform>
            <translate value="0, 3, -2"/>
        </transform>
        <point_light color="0.1, 1.0, 0.1" intensity="30.0" attenuation="1.0" radius="15.0"/>
    </entity>
</scene>

=== kiinami/lisa-vulkan/scenes/cbox/cbox.xml
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../scene.xsd">
    <entity name="cat">
        <transform>
            <translate value="-1, 0, 0"/>
            <scale value="10.0"/>
        </transform>
        <mesh path="models/cat.obj"/>
        <material albedo_texture="textures/concrete_cat_statue_diff_1k.jpg"
                  roughness_texture="textures/concrete_cat_statue_rough_1k.exr"
                  metallic_texture="textures/concrete_cat_statue_metal_1k.exr"
                  normal_texture="textures/concrete_cat_statue_nor_gl_1k.exr"
        />
    </entity>

    <entity name="sphere1">
        <transform>
            <translate value="1, 0.5, 1"/>
            <scale value="0.5"/>
        </transform>
        <mesh path="models/sphere.obj"/>
        <material albedo="1.0 0.0 1.0" roughness="0.05" metallic="0.0"/>
    </entity>
    <entity name="sphere2">
        <transform>
            <translate value="0, 0.5, 2"/>
            <scale value="0.5"/>
        </transform>
        <mesh path="models/sphere.obj"/>
        <material albedo="0.0 1.0 0.0" roughness="1.0" metallic="0.0"/>
    </entity>
    <entity name="sphere3">
        <transform>
            <translate value="-2, 0.5, 2"/>
            <scale value="0.5"/>
        </transform>
        <mesh path="models/sphere.obj"/>
        <material albedo="0.0 0.0 1.0" roughness="0.2" metallic="0.9"/>
    </entity>
    <entity name="sphere4">
        <transform>
            <translate value="-3, 0.5, 1"/>
            <scale value="0.5"/>
        </transform>
        <mesh path="models/sphere.obj"/>
        <material albedo="1.0 0.0 0.0" roughness="1" metallic="1"/>
    </entity>

    <entity name="walls">
        <transform>
            <translate value="0, 0, 0"/>
            <scale value="4"/>
        </transform>
        <mesh path="models/walls2.obj"/>
        <material albedo="1.0 0.1 0.1" roughness="0.05" metallic="0.0"/>
    </entity>

    <entity name="main_camera">
        <transform>
            <lookat origin="0, 3, 15" target="0, 3, 0" up="0, 1, 0"/>
        </transform>
        <camera/>
    </entity>

    <entity name="light">
        <transform>
            <lookat origin="0, 7, 3" target="0, 3, 0" up="0, 1, 0"/>
        </transform>
        <directional_light color="1.0, 0.8, 0.7" intensity="2" cast_shadows="true"/>
        <point_light color="1.0, 0.8, 0.7" intensity="10" attenuation="1" radius="100" cast_shadows="true"/>
        <ambient_light color="1.0, 0.8, 0.7" intensity="0.05"/>
    </entity>
</scene>
