=== kiinami/lisa-vulkan/assets/rendergraphs/rendergraph.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="ResourceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="color"/>
            <xs:enumeration value="depth"/>
            <xs:enumeration value="final"/>
            <xs:enumeration value="normal"/>
            <xs:enumeration value="position"/>
            <xs:enumeration value="material"/>
            <xs:enumeration value="ssao"/>
            <xs:enumeration value="shadow_depth"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PassType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="preprocess::depth"/>
            <xs:enumeration value="preprocess::ssao"/>
            <xs:enumeration value="preprocess::ssao_blur"/>
            <xs:enumeration value="forward"/>
            <xs:enumeration value="deferred::geometry"/>
            <xs:enumeration value="deferred::composition"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ResourceUsage">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ColorAttachmentWrite"/>
            <xs:enumeration value="DepthStencilAttachmentWrite"/>
            <xs:enumeration value="DepthStencilAttachmentRead"/>
            <xs:enumeration value="SampledFragment"/>
            <xs:enumeration value="StorageComputeWrite"/>
            <xs:enumeration value="TransferSrc"/>
            <xs:enumeration value="TransferDst"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="rendergraph">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="resource" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="type" type="ResourceType" use="required"/>

                        <xs:attribute name="width" type="xs:positiveInteger"/>
                        <xs:attribute name="height" type="xs:positiveInteger"/>

                        <xs:attribute name="scale">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="0.0"/>
                                    <xs:maxInclusive value="1.0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <xs:assert test="
                            (
                                exists(@scale)
                                and not(exists(@width) or exists(@height))
                            )
                            or
                            (
                                exists(@width)
                                and exists(@height)
                                and not(exists(@scale))
                            )
                            or
                            (
                                not(exists(@scale))
                                and not(exists(@width))
                                and not(exists(@height))
                            )
                        "/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="pass" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="value" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="input" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="ref" type="xs:IDREF" use="required"/>
                                    <xs:attribute name="usage" type="ResourceUsage" use="required"/>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="output" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="ref" type="xs:IDREF" use="required"/>
                                    <xs:attribute name="usage" type="ResourceUsage" use="required"/>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>

            <xs:attribute name="output" type="xs:IDREF" use="required"/>
            <xs:attribute name="profile" type="xs:string" use="required"/>

        </xs:complexType>
    </xs:element>

</xs:schema>

=== kiinami/lisa-vulkan/assets/rendergraphs/deferred_rtx.xml
<rendergraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="rendergraph.xsd"
             output="final"
             profile="raytracing">
    <resource id="depth" type="depth"/>
    <resource id="albedo" type="color"/>
    <resource id="normal" type="normal"/>
    <resource id="position" type="position"/>
    <resource id="material" type="material"/>
    <resource id="ssao" type="ssao"/>
    <resource id="ssao_blurred" type="ssao"/>
    <resource id="final" type="final"/>

    <pass id="depth_pass" type="preprocess::depth">
        <output id="depth" ref="depth" usage="DepthStencilAttachmentWrite"/>
    </pass>

    <pass id="geometry_pass" type="deferred::geometry">
        <input id="depth" ref="depth" usage="DepthStencilAttachmentRead"/>
        <output id="albedo" ref="albedo" usage="ColorAttachmentWrite"/>
        <output id="normal" ref="normal" usage="ColorAttachmentWrite"/>
        <output id="position" ref="position" usage="ColorAttachmentWrite"/>
        <output id="material" ref="material" usage="ColorAttachmentWrite"/>
    </pass>

    <pass id="ssao_pass" type="preprocess::ssao">
        <input id="depth" ref="depth" usage="SampledFragment"/>
        <input id="position" ref="position" usage="SampledFragment"/>
        <input id="normal" ref="normal" usage="SampledFragment"/>
        <output id="ssao" ref="ssao" usage="ColorAttachmentWrite"/>
    </pass>

    <pass id="ssao_blur_pass" type="postprocess::convolutional">
        <parameter id="kernel">
            1 1 1 1 1
            1 1 1 1 1
            1 1 1 1 1
            1 1 1 1 1
            1 1 1 1 1
        </parameter>
        <input id="input" ref="ssao" usage="SampledFragment"/>
        <output id="output" ref="ssao_blurred" usage="ColorAttachmentWrite"/>
    </pass>

    <pass id="composition_rtx_pass" type="deferred::composition_rtx">
        <input id="albedo" ref="albedo" usage="SampledFragment"/>
        <input id="normal" ref="normal" usage="SampledFragment"/>
        <input id="position" ref="position" usage="SampledFragment"/>
        <input id="material" ref="material" usage="SampledFragment"/>
        <input id="ssao" ref="ssao_blurred" usage="SampledFragment"/>
        <output id="final" ref="final" usage="ColorAttachmentWrite"/>
    </pass>

</rendergraph>

=== kiinami/lisa-vulkan/assets/rendergraphs/deferred.xml
<rendergraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="rendergraph.xsd"
             output="final">
    <resource id="depth" type="depth"/>
    <resource id="albedo" type="color"/>
    <resource id="normal" type="normal"/>
    <resource id="position" type="position"/>
    <resource id="material" type="material"/>
    <resource id="final" type="final"/>

    <pass id="depth_pass" type="depth">
        <output id="depth" ref="depth" usage="DepthStencilAttachmentWrite"/>
    </pass>
    <pass id="geometry_pass" type="deferred::GeometryPass">
        <input id="depth" ref="depth" usage="DepthStencilAttachmentRead"/>
        <output id="albedo" ref="albedo" usage="ColorAttachmentWrite"/>
        <output id="normal" ref="normal" usage="ColorAttachmentWrite"/>
        <output id="position" ref="position" usage="ColorAttachmentWrite"/>
        <output id="material" ref="material" usage="ColorAttachmentWrite"/>
    </pass>
    <pass id="composition_pass" type="deferred::CompositionPass">
        <input id="albedo" ref="albedo" usage="SampledFragment"/>
        <input id="normal" ref="normal" usage="SampledFragment"/>
        <input id="position" ref="position" usage="SampledFragment"/>
        <input id="material" ref="material" usage="SampledFragment"/>
        <output id="final" ref="final" usage="ColorAttachmentWrite"/>
    </pass>
</rendergraph>

=== kiinami/lisa-vulkan/assets/rendergraphs/ssao_test.xml
<rendergraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="rendergraph.xsd"
             output="final">

    <resource id="depth" type="depth"/>
    <resource id="albedo" type="color"/>
    <resource id="normal" type="normal"/>
    <resource id="position" type="position"/>
    <resource id="material" type="material"/>
    <resource id="final" type="final"/>

    <pass id="depth_pass" type="preprocess::depth">
        <output id="depth" ref="depth" usage="DepthStencilAttachmentWrite"/>
    </pass>

    <pass id="geometry_pass" type="deferred::geometry">
        <input id="depth" ref="depth" usage="DepthStencilAttachmentRead"/>
        <output id="albedo" ref="albedo" usage="ColorAttachmentWrite"/>
        <output id="normal" ref="normal" usage="ColorAttachmentWrite"/>
        <output id="position" ref="position" usage="ColorAttachmentWrite"/>
        <output id="material" ref="material" usage="ColorAttachmentWrite"/>
    </pass>

    <pass id="ssao_pass" type="preprocess::ssao">
        <input id="depth" ref="depth" usage="SampledFragment"/>
        <input id="position" ref="position" usage="SampledFragment"/>
        <input id="normal" ref="normal" usage="SampledFragment"/>
        <output id="ssao" ref="final" usage="ColorAttachmentWrite"/>
    </pass>
</rendergraph>
